import React from "react";
import type { Metadata } from "next";
import PriceChangeIcon from '@mui/icons-material/PriceChange';
import { Stack, Box, Typography } from "@mui/material";
import { Inter, Press_Start_2P } from "next/font/google";
import Grid from "@/components/Grid/Grid";

import "./globals.css";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });
const pressStart2p = Press_Start_2P({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <React.StrictMode>
          <StoreProvider>
            <Stack alignItems={"center"} justifyContent={"center"} sx={{ marginBottom: 8 }} direction={"row"} spacing={1}>
              <Typography className={pressStart2p.className} variant="h5" sx={{textShadow: "1px 1px 1px black"}}>
                Welcome to Cryptoverse
              </Typography>
              <PriceChangeIcon fontSize="large" />
            </Stack>
            {children}
            
          </StoreProvider>
        </React.StrictMode>
      </body>
    </html>
  );
}
